import React from "react"
import { Link } from "gatsby"

import Layout from "../components/layout"
import SEO from "../components/seo"

const SecondPage = () => (
  <Layout>
    <SEO title="Impressum" />
    <h2>Disclaimer</h2>
    <h3>Google Analytics</h3>
    This website uses Google Analytics, a web analytics service provided by
    Google, Inc. ("Google"). Google Analytics uses "cookies", which are text
    files placed on your computer to help the website analyse how visitors use
    the site. The information generated by the cookie about your use of the
    website (including your IP address) will be transmitted to and stored by
    Google on servers in the United States . Google will use this information
    for the purpose of evaluating your use of the website, compiling reports on
    website activity for website operators and providing other services relating
    to website activity and internet usage. Google may also transfer this
    information to third parties where required to do so by law, or where such
    third parties process the information on Google's behalf. Google will not
    associate your IP address with any other data held by Google. You may refuse
    the use of cookies by selecting the appropriate settings on your browser,
    however please note that if you do this you may not be able to use the full
    functionality of this website. By using this website, you consent to the
    processing of data about you by Google in the manner and for the purposes
    set out above.
    <br />
    <br />
    You can prevent Google’s collection and use of data (cookies and IP address)
    by downloading and installing the browser plug-in available under
    https://tools.google.com/dlpage/gaoptout?hl=en.
    <br />
    <br />
    Please note that this website initializes Google Analytics with the setting
    anonymizeIp. This guarantees anonymized data collection by masking the last
    part of your IP address.
    <br />
    <br />
    Further information concerning the terms and conditions of use and data
    privacy can be found at http://www.google.com/analytics/terms/gb.html or at
    http://www.google.com/intl/en_uk/analytics/privacyoverview.html.
    <br />
    <br />
    <h3>Contact Form Information </h3>
    Garden will store the personal information provided on the "Request a Demo"
    form to be able to contact you back with the content requested. If you would
    like this information removed from our systems, please contact us at
    info@garden.io. Garden does not track cookies when submitting this form nor
    does Garden use your IP address. Furthermore, Garden will not use this
    information for email marketing. If you would like to subscribe to our
    newsletter, please use our subscription form.
    <br />
    <br />
    <h3>Email Marketing</h3>
    Garden will use the email address provided on the subscription form to be in
    touch with you and to provide updates and marketing. You can change your
    mind at any time by clicking the unsubscribe link in the footer of any email
    you receive from us, or by contacting us at hello@garden.io.
    <br />
    <br />
    We will treat your information with respect and ask for your permission both
    when signing up on our website and again via a “Confirm Subscription” email.
    This ensures your email address or any other personal information will not
    be stored unless with your absolute consent.
    <br />
    <br />
    We use MailChimp as our marketing automation platform. By submitting the
    contact form, you acknowledge that the information you provide will be
    transferred to MailChimp for processing in accordance with their Privacy
    Policy and Terms.
  </Layout>
)

export default SecondPage
